### ISSUE TITLE
Cannot validate & pack serverless_request_app from examples

### ISSUE THREAD

**Issue by martinlazarov** [freshdesk/marketplace-sample-apps#5]
Hello, Freshdesk team!

I receive an error when I try to Validate / Pack the Example serverless_request_app.

Steps to reproduce:

1. Clone the repository
2. Navigate to serverless_request_app  (No change is made in the Application's code)
3. Run in terminal fdk validate / fdk pack
4. Error is displayed:

>$ fdk pack
Packing failed due to the following issue(s):
The following dependencies are not used: request

>$ fdk validate
Validation failed due to the following issue(s):
The following dependencies are not used: request

Environment:
>$ node -v
v8.9.4

OS: Windows 10

I am looking forward for your response!

Thank you in advance,
Martin Lazarov

**Comment by satwikhebbar** [comment]
Hello Martin,

Thank you for reaching out. And sorry it took a while getting back to you here.

We do have a bug in our fdk tool with respect to running on Windows. A fix for the same will be published shortly, after which we will notify you. 

Thank you for your patience meanwhile.

**Comment by masterminduday** [comment]
Hello Freshdesk Team,

Even I am facing the same issue. Awaiting an update to the fdk tool.

**Comment by masterminduday** [comment]
![fdk pack error_1](https://user-images.githubusercontent.com/593894/36411477-da9fcfe8-163b-11e8-95a7-fd82ae998687.png)

**Comment by destinarian** [comment]
I am having the same issue. 
Error: "The following dependencies are not used: request"

Any update how to resolve this? Any temporary fix whilst an update a fdk come?

**Comment by masterminduday** [comment]
@dineshvgp Even after an update to fdk to 4.2.0 still the issue isn't resolved for validating a servless request app.

**Comment by masterminduday** [comment]
@freshdesk

**Comment by satwikhebbar** [comment]
Hello @masterminduday @destinarian @martinlazarov There is a new version of the FDK - 4.2.1 - which is now available. This addresses the problem described here.

Apologies for taking a long time to address this problem. We were not actively including Windows within our test environment for the FDK earlier. We now put in the effort ensure our test suites can run against Windows environments as well, which is why this took longer than you might expect. 

Thanks for your patience.
